version: '2'
services:
  admin:
    build: ./admin
    container_name: admin
    environment: 
      - NODE_ENV=prod
    ports: 
      - "8081:12306"
    volumes: 
      - ./admin:/var/app
    expose: 
      - "12306"
  web:
    image: nginx
    container_name: www
    ports:
      - "80:80"
    volumes:
      - ./nginx/local:/etc/nginx/conf.d
      - ./www/dist:/app/www
      - ./backend/dist:/app/backend
  mongo:
    image: mongo
    container_name: db
    command: ['--auth']
    ports:
      - "10010:27017"
    volumes: 
      - ./db/server:/data/db