version: '2'
services:
  admin:
    build: ./admin
    container_name: admin
    environment: 
      - NODE_ENV=prod
    ports: 
      - "8081:12306"
    volumes: 
      - ./admin:/var/app
    expose: 
      - "12306"
  web:
    image: nginx
    container_name: www
    ports:
      - "81:80"
    volumes:
      - ./nginx/local:/etc/nginx/conf.d
      - ./www/dist:/app/www
      - ./backend/dist:/app/backend
  mongo:
    image: tutum/mongodb
    container_name: db_test
    environment:
      - MONGODB_USER=mysite
      - MONGODB_DATABASE=mysite
      - MONGODB_PASS=123456
    ports:
      - "10010:27017"
    volumes: 
      - ./db/local:/data/db